// frontend-react/src/components/Buttons.jsx
import * as React from 'react';
import './App.css'

export default function Buttons(props) {
    return (
        <div className="row">
            <div className="col-md-12 text-center Margin">
                <button className="btn btn-primary Margin-1" onClick={props.login}>Login</button>
                <button className="btn btn-dark Margin-1" onClick={props.logout}>Logout</button>
            </div>
        </div>
    )
}

// frontend-angular/src/app/components/buttons/buttons.component.ts
import {Component, EventEmitter, Output} from '@angular/core';

@Component({
  selector: 'app-buttons',
  standalone: true,
  imports: [],
  templateUrl: './buttons.component.html',
  styleUrl: './buttons.component.css'
})
export class ButtonsComponent {
  @Output() loginEvent = new EventEmitter();
  @Output() logoutEvent = new EventEmitter();

}

<div class="row">
<div class="login">
  <div class="col-md-12 text-center">
    <button class="btn btn-primary" (click)="loginEvent.emit()">
      Login
    </button>
    <button class="btn btn-dark" (click)="logoutEvent.emit()">
      Logout
    </button>
  </div>
</div>
</div>
