// frontend-react/src/components/LoginForm.jsx
import React from 'react';
import classNames from 'classnames';

export default class LoginForm extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            active: "login",
            firstName: "",
            lastName: "",
            login: "",
            password: "",
            onLogin: props.onLogin,
            onRegister: props.onRegister
        }
    }

    onChangeHandler = (event) => {
        let name = event.target.name;
        let value = event.target.value;
        this.setState({[name]: value});
    };

    onSubmitLogin = (e) => {
        this.state.onLogin(e, this.state.login, this.state.password)
    }

    onSubmitRegister = (e) => {
        this.state.onRegister(
        e,
            this.state.firstName,
            this.state.lastName,
            this.state.login,
            this.state.password)
        ;
    }

    render(){
        return (
            <div className="row justify-content-center">
                <div className="col-4">
                    <ul className="nav nav-pills nav-justified mb-3" id="ex1" role="tablist">
                        <li className="nav-item" role="presentation">
                            <button className={classNames("nav-link", this.state.active === "login" ? "active" : "")}
                                    id="tab-login" onClick={() => this.setState({active: "login"})}>Login
                            </button>
                        </li>
                        <li className="nav-item" role="presentation">
                            <button className={classNames("nav-link", this.state.active === "register" ? "active" : "")}
                                    id="tab-login" onClick={() => this.setState({active: "register"})}>Register
                            </button>
                        </li>
                    </ul>
                    <div className="tab-content">
                        <div
                            className={classNames("tab-pane", "fade", this.state.active === "login" ? "show active" : "")} id="pills-login">
                            <form onSubmit={this.onSubmitLogin}>
                                <div className="form-outline mb-4">
                                    <input type="login" id="loginName" name="login" className="form-control" onChange={this.onChangeHandler}/>
                                    <label className="form-label" htmlFor="loginName">Username</label>
                                </div>
                                <div className="form-outline mb-4">
                                    <input type="password" id="loginPassword" name="password" className="form-control" onChange={this.onChangeHandler}/>
                                    <label className="form-label" htmlFor="loginPassword">Password</label>
                                </div>

                                <button type="submit" className="btn btn-primary btn-block mb-4">Sign in</button>
                            </form>
                        </div>
                    </div>
                    <div className="tab-content">
                        <div
                            className={classNames("tab-pane", "fade", this.state.active === "register" ? "show active" : "")} id="pills-register">
                            <form onSubmit={this.onSubmitRegister}>
                                <div className="form-outline mb-4">
                                    <input type="text" id="firstName" name="firstName" className="form-control" onChange={this.onChangeHandler}/>
                                    <label className="form-label" htmlFor="firstName">First Name</label>
                                </div>
                                <div className="form-outline mb-4">
                                    <input type="text" id="lastName" name="lastName" className="form-control" onChange={this.onChangeHandler}/>
                                    <label className="form-label" htmlFor="lastName">Last Name</label>
                                </div>
                                <div className="form-outline mb-4">
                                    <input type="text" id="userName" name="userName" className="form-control" onChange={this.onChangeHandler}/>
                                    <label className="form-label" htmlFor="userName">Username</label>
                                </div>
                                <div className="form-outline mb-4">
                                    <input type="password" id="loginPassword" name="password" className="form-control" onChange={this.onChangeHandler}/>
                                    <label className="form-label" htmlFor="loginPassword">Password</label>
                                </div>

                                <button type="submit" className="btn btn-primary btn-block mb-4">Sign in</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        )
    }
}

// frontend-angular/src/app/components/login-form/login-form.component.ts
import {Component, EventEmitter, Output} from '@angular/core';
import {NgClass} from "@angular/common";
import {FormsModule} from "@angular/forms";

@Component({
  selector: 'app-login-form',
  standalone: true,
  imports: [
    NgClass,
    FormsModule
  ],
  templateUrl: './login-form.component.html',
  styleUrl: './login-form.component.css'
})
export class LoginFormComponent {

  @Output() onSubmitLoginEvent = new EventEmitter();
  @Output() onSubmitRegisterEvent = new EventEmitter();

  active: string = "login";
  firstName: string = "";
  lastName: string = "";
  login: string = "";
  password: string = "";

  onLoginTab(): void {
    this.active = "login";
  }

  onRegisterTab(): void {
    this.active = "register";
  }

  onSubmitLogin(): void {
    this.onSubmitLoginEvent.emit({"login": this.login, "password": this.password});
  }

  onSubmitRegister(): void {
    this.onSubmitRegisterEvent.emit({"firstName": this.firstName, "lastName": this.lastName, "login": this.login, "password": this.password});
  }

}

<div class="row justify-content-center">
  <div class="col-4">
    <ul class="nav nav-pills nav-justified mb-3" id="ex1" role="tablist">
      <li class="nav-item" role="presentation">
        <button [ngClass]="active == 'login' ? 'nav-link active' : 'nav-link'" id="tab-login"
                (click)="onLoginTab()" >Login</button>
      </li>
      <li class="nav-item" role="presentation">
        <button [ngClass]="active == 'register' ? 'nav-link active' : 'nav-link'" id="tab-register"
                (click)="onRegisterTab()" >Register</button>
      </li>
    </ul>

    <div class="tab-content">
      <div [ngClass]="active == 'login' ? 'tab-pane fade show active' : 'tab-pane fade'">
        <form (ngSubmit)="onSubmitLogin()" #loginForm="ngForm">

          <div class="form-outline mb-4">
            <input type="login" id="loginName" name= "login" class="form-control" [(ngModel)]="login" />
            <label class="form-label" for="loginName">Username</label>
          </div>

          <div class="form-outline mb-4">
            <input type="password" id="loginPassword" name="password" class="form-control" [(ngModel)]="password" />
            <label class="form-label" for="loginPassword">Password</label>
          </div>

          <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>

        </form>
      </div>
      <div [ngClass]="active == 'register' ? 'tab-pane fade show active' : 'tab-pane fade'">
        <form (ngSubmit)="onSubmitRegister()" #registerForm="ngForm">

          <div class="form-outline mb-4">
            <input type="text" id="firstName" name="firstName" class="form-control" [(ngModel)]="firstName" />
            <label class="form-label" for="firstName">First name</label>
          </div>

          <div class="form-outline mb-4">
            <input type="text" id="lastName" name="lastName" class="form-control" [(ngModel)]="lastName" />
            <label class="form-label" for="lastName">Last name</label>
          </div>

          <div class="form-outline mb-4">
            <input type="text" id="login" name="login" class="form-control" [(ngModel)]="login" />
            <label class="form-label" for="login">Username</label>
          </div>

          <div class="form-outline mb-4">
            <input type="password" id="registerPassword" name="password" class="form-control" [(ngModel)]="password" />
            <label class="form-label" for="registerPassword">Password</label>
          </div>

          <button type="submit" class="btn btn-primary btn-block mb-3">Sign in</button>
        </form>
      </div>
    </div>
  </div>
</div>
