// frontend-react/src/components/App.jsx
import './App.css'
import logo from '../logo.svg'
import Header from './Header'
import AppContent from './AppContent';


function App() {
  return (
    <div>
      <Header pageTitle="Frontend authenticated with JWT" logoSrc={logo} />
      <div className="container-fluid">
        <div className="row">
          <div className="col">
            <AppContent />
          </div>
        </div>
      </div>
    </div>
  )
}

export default App;

// frontend-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import {HeaderComponent} from "./header/header.component";

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, HeaderComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'frontend-angular';
}

<div>
  <app-header [pageTitle]="'Frontend authenticated with JWT'" [logoSrc]="'assets/images/logo.png'" />
  <div class="container-fluid">
    <div class="row">
      <div class="col">
        <app-content />
      </div>
    </div>
  </div>
</div>
